name: emsim
channels:
- defaults
dependencies:
- arrow=0.13.1
- future=0.16.0
- numpy=1.18.1
- pandas=1.0.3
- pip=20.0.2
- python=3.7.6
- requests=2.23.0
- scipy=1.4.1
- pip:
    - geojson==2.3.*
    - polyline==1.3.*
    - geopy==1.21.*
    - attrdict==2.0.0
    - bson==0.5.9
