on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  example-1:

    runs-on: ubuntu-latest
    steps:
      - uses: goanpeca/setup-miniconda@v1.0.2
        with:
            activate-environment: ''
      - name: Conda info
        shell: bash -l {0}
        run: |
            python --version
            conda info
            conda --version
            conda env list
            python --version
            conda activate base
            conda env list
            python --version
